# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Area.create(:name => '鶴舞')
Area.create(:name => '吹上')
Area.create(:name => '御器所')
Area.create(:name => '荒畑')
Area.create(:name => '千種')

Category.create(:name => 'ラーメン')
Category.create(:name => 'まぜそば')
Category.create(:name => 'つけ麺')
Category.create(:name => 'チャーハン')
Category.create(:name => '餃子')
Category.create(:name => 'そば')
Category.create(:name => 'うどん')
Category.create(:name => '中華')
Category.create(:name => '定食')
Category.create(:name => 'カレー')
Category.create(:name => 'カフェ・喫茶店')
Category.create(:name => 'イタリアン')
Category.create(:name => 'ジャンクフード')
Category.create(:name => 'ハンバーガー')
Category.create(:name => '焼肉')
Category.create(:name => 'どんぶり')
Category.create(:name => '寿司')
Category.create(:name => 'コンビニ')
Category.create(:name => '軽食')
Category.create(:name => 'ファミレス')
Category.create(:name => '手羽先')
Category.create(:name => '揚げ物')
Category.create(:name => '隠れ家')
Category.create(:name => '居酒屋')


User.create(:email => 'test1@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test2@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test3@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test4@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test5@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test6@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test7@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test8@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test9@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test10@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test11@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test12@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test13@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test14@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test15@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test16@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test17@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test18@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test19@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test20@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test21@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test22@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test23@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test24@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test25@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test26@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test27@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test28@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test29@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test30@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test31@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test32@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test33@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test34@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test35@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test36@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test37@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test38@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test39@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test40@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test41@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test42@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test43@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test44@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test45@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test46@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test47@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test48@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test49@test.com', :password =>  'password', :password_confirmation => 'password')
User.create(:email => 'test50@test.com', :password =>  'password', :password_confirmation => 'password')



1.upto(50){ |i|
    Mypage.create(:name => %(test"#{i}"), :user_id => i)
}

Shop.create(:name => "shop1", :address => "toriaezu", :latitude => "35.1527163106303", :longitude => "136.930525302887")


